version: '3.4'

networks:
  tracing:
    name: tracing-network
    
services:

  otel:
    image: amazon/aws-otel-collector:latest
    command: --config /config/config.yml
    volumes:
      - ./aws-otel-collector-config:/config
    environment:
      - AWS_ACCESS_KEY_ID=<ADD-AWS-USER-ACCESS-KEY>
      - AWS_SECRET_ACCESS_KEY=<ADD-AWS-USER-SECRET-KEY>
      - AWS_REGION=eu-west-1
    ports:
      - 4317:4317
    networks:
      - tracing

  app1:
    build:
      context: ./App1.WebApi
    ports:
      - "5000:80"
    networks:
      - tracing
    depends_on: 
      - otel
      - app3
    environment:
      RABBITMQ__HOST: <ADD-AMAZONMQ-RABBIT-HOST-ENDPOINT>
      RABBITMQ__USERNAME: specialguest
      RABBITMQ__PASSWORD: P@ssw0rd111!
      APP3ENDPOINT: http://app3/dummy
      OTLP__ENDPOINT: http://otel:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=App1

  app2:
    stdin_open: true
    tty: true
    build:
      context: ./App2.RabbitConsumer.Console
    networks:
      - tracing
    depends_on: 
      - otel
      - app3
    environment:
      RABBITMQ__HOST: <ADD-AMAZONMQ-RABBIT-HOST-ENDPOINT>
      RABBITMQ__USERNAME: specialguest
      RABBITMQ__PASSWORD: P@ssw0rd111!
      APP3URIENDPOINT: http://app3
      OTLP__ENDPOINT: http://otel:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=App2


  app3:
    build:
      context: ./App3.WebApi
    ports:
      - "5001:80"
    networks:
      - tracing
    depends_on: 
      - otel
    environment:
      OTLP__ENDPOINT: http://otel:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=App3
      S3__BUCKETNAME: <ADD-S3-BUCKET-NAME>
      SQS__URI: <ADD-SQS-URI>
      AWS_ACCESS_KEY_ID: <ADD-AWS-USER-ACCESS-KEY>
      AWS_SECRET_ACCESS_KEY: <ADD-AWS-USER-SECRET-KEY>
  
  app4:
    build:
      context: ./App4.SqsConsumer.HostedService
    networks:
      - tracing
    depends_on: 
      - otel
    environment:
      OTLP__ENDPOINT: http://otel:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=App4
      SQS__URI: <ADD-SQS-URI>
      AWS_ACCESS_KEY_ID: <ADD-AWS-USER-ACCESS-KEY>
      AWS_SECRET_ACCESS_KEY: <ADD-AWS-USER-SECRET-KEY>

  
