receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: eu-west-1


service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - logging
        - awsxray